### PR TITLE
Key combination mapping

### PR DESCRIPTION
**Pull request by Fruity-0**
Somehow it would turn off this option (or change the "M2" mapping) without disabling the "CTRL + Drag" combination in the camera / strafe mode settings?

Screenshot_1

### CODE REVIEW

**Comment by Garux** [comment]
I don't know what your pull request would do, as it is huge and has conflicts.

**Comment by Fruity-0** [comment]
I do not know if I did not mix something on GitHub, for the first time I add information here and I had to press something to add it.
As for your speech, I do not understand very well. It is possible that I wrote it incorrectly (my English is poor). I mean disabling or bypassing (somehow) sideways movement when right-clicking on the 3D window, I have used the CTRL key for a long time for this operation and I like full freedom of movement in the 3D window (this habit: - /), I really like the number of options added in the new ZeroRadiant (very sensible options at the time of creation), a lot of good work and the little detail written above, I am a little irritating (unfortunately such a habit to older GTKRadiant 1.5)

**Comment by Garux** [comment]
Requests w/o code go to `Issues` in github.  
Right-clicking on the 3D window enters regular mouselook mode. Holding right mouse button and moving mouse does strafe move; idea behind this is to have uniform behavior for this action in 2D, 3D and texture browser.  
ZeroRadiant is gtk radiant 1.4 with a few fixes.  
This one's history is: GtkRadiant 1.4→massive rewrite→1.5→NetRadiant→this

As for your speech, I do not understand very well. It is possible that I wrote it incorrectly (my English is poor). I mean disabling or bypassing (somehow) sideways movement when right-clicking on the 3D window, I have used the CTRL key for a long time for this operation and I like full freedom of movement in the 3D window (this habit: - /), I really like the number of options added in the new ZeroRadiant (very sensible options at the time of creation), a lot of good work and the little detail written above, I am a little irritating (unfortunately such a habit to older GTKRadiant 1.5)

**Comment by Fruity-0** [comment]
I understand the concepts of this solution. It will be difficult for me to get used to it but we will try :-).
Thanks for the information.

**Comment by Garux** [comment]
Adding option of action to do during m2 camera drag sounds like an idea, i think, just non first priority one.  
What's your use scenario, which is confusing? Do you do mouse look with m2 pressed?

**Comment by Fruity-0** [comment]
Recently, I started using NetRadiant a little more and I noticed that this combination of M2 + drag traffic (strafe traffic) is quite decent, at least I think so :-) (I just have to get used to it). In general, we'll see what comes out in the wash, and I do not want to poison my head here, because this is not a programming error, but my suggestion.
Nevertheless, the option of changing the keys on the mouse would be appreciated in the future.

**Comment by Garux** [comment]
Such controls are usable.  
I'm not sure, if i understand your previous comment correctly, so showing, how it should work, i.e. strafe and like-in-game moves are available simultaneously:

**Comment by Fruity-0** [comment]
However, after prolonged use, this option is very good, everything works. Subject to close

**Pull request closed without merging**
