### PR TITLE
Language Support

### PR DESCRIPTION
**Pull request by Tom362-a**
Hello
Question regarding the topic:
1. Is it possible to implement the "menu bar" language selection and all "NetRadiant" global settings? And could I possibly translate (somehow) the source file into my native language and send it for deployment in the next update?
As you know, it is better to learn the original language of the creators (English), for various types of guides on the Internet, etc., so the suggestion is more optional than priority.

### CODE REVIEW

**Comment by Garux** [comment]
Perhaps translations would be nice to have, afaik GTK has built-in mechanism to support interface translations.
On the other hand having the only international laguage used can be considered, as advantage of guaranteed ability to understand and to be understood after learning just a few specific terms.

**Comment by Fruity-0** [comment]
Welcome back.
I reopen the thread as I forgot a few points that I wanted to add on this topic, but somehow it came out of my head and closed it. All in all, I could write on the Discord channel, but I think it's good if there is continuity in the thread. I also write because of the arrival of new people (from my country) who too
begin their adventure with NetRadiant.
Not extending it, it is about the possibility of translating (certain interface groups), but leaving the original names as they are so far.
For example: 
By setting a given interface language, everything would be the same by default, but would appear in translation brackets or abbreviated words for understanding. These parentheses could be appended with a space after the original characters, depending on the available space in the GUI.

My guess is it might be a lot of work or time to devote to it.
If possible, I would like to consider this suggestion in the future.

**Comment by Garux** [comment]
Adding translated text next to engligh notation will overload interface for sure.  
What could work is having translation in tooltips.

**Comment by Fruity-0** [comment]
"...translation in tooltips."
Do you mean the HELP tab in the MENU?

**Comment by Garux** [comment]
image
this

**Comment by Fruity-0** [comment]
:-O I didn't know NetRadiant had it. Sounds reasonable. If there was a possibility, I would like to translate it, at least for checking (test)

**Comment by NeonKnightOA** [comment]
I'm all for supporting the number one historic anti-frustration/quality-of-life feature that is language localization. Even if there's english it would be neat if the option to let people map in their own language exist.

**Pull request closed without merging**
