### PR TITLE
Last of @illwieckz updates to the packs.

### PR DESCRIPTION
**Pull request by NeonKnightOA**

### CODE REVIEW

**Comment by Garux** [comment]
@NeonKnightOA
i squashed all these edits to single commit for cleaner history (hopefully everything went fine:3)
btw: can you shed some light on topic of q3pack being proprietary? I'm not experienced in this question; What files are proprietary? What files are ok to include in releases?

**Comment by NeonKnightOA** [comment]
From what I've read on the OpenArena forum, the problem lies in the entity files.
Some help texts are not in the source files and are considered "original work". This was why the devs of NetRadiant asked for a GPL'd Quake III pack.

http://openarena.ws/board/index.php?topic=2722.0

**Comment by Garux** [comment]
Ic this note:
>the license of the original Q3 pack is not clearly stated anywhere

+.def and .ent were distributed along with Radiants 1.4/1.6 and 1.5 (licensed under GPL)
Is it legit to distribute proprietary texts with GPL soft?

Also Wolf, ET, JA packs are included in 1.6 releases, but marked, as proprietary here
Also we are missing link to UrT pack :)

**Comment by NeonKnightOA** [comment]
Well, the source files for the three test maps (q3dm1, q3dm7 and q3dm17) and the terrain demo for Team Arena plus all of their respective assets were also distributed in that gamepack, yet (as far as I recall) those maps aren't exactly GPL'd. The same case can be done for the entity files, considering that, during a long time, OA's gamepack license couldn't be cleared off because those files were extracted directly from Q3. So the safer choice was to assume those packs are propietary.

**Pull request merged**
